### ISSUE TITLE
triple dot needs "Edit" in editor

### ISSUE THREAD

**Issue by crutkas** [JaneaSystems/PowerToys-DevProjects#36] opened 2024-06-13 20:41 UTC
![image](https://github.com/JaneaSystems/PowerToys-DevProjects/assets/1462282/8aea90ac-8f64-4030-af21-edf7de39a216)
While clicking on main body does launch, i could still see ... menu item.

**Comment by noraa-junker** [comment] 2024-06-13 20:44
duplicate of #23

**Closed as completed** 2024-06-14 01:08 UTC
